# rows_dict={
#     'ImageId':[],
#     'Labels':[],
#     'dog':[],
#     'buffalo':[],
#     'cat':[],
#     'cow':[],
#     'pig':[],
#     'sheep':[],
#     'goat':[],
#     'hen':[],
#     'applered':[],
#     'banana':[],
#     'watermelon':[],
#     'papaya':[],
#     'mosambi':[],
#     'lemon':[],
#     'grapeblue':[],
#     'grapewhite':[],
#     'pomegranate':[],
#     'coconut':[],
#     'orange':[],
#     'pineapple':[],
# 'kiwi':[],
# 'jamunfruit':[],
# 'iceapple':[],
# 'raspberry':[],
# 'custardapple':[],
# 'avocado':[],
# 'cherry':[],
# 'mango':[],
# 'guava':[]
# }

rows_dict={
    'ImageId':[],
    'Labels':[],
    'carrot':[],
    'ginger':[],
    'greenchilli':[],
    'tomato':[],
    'pumpkin':[],
    'ladiesfinger':[],
    'onion':[],
    'bittergourd':[],
    'brinjal':[],
    'cucumber':[],
    'garlic':[],
    'potato':[],
    'capsicum':[]
}

